import { createSdkMcpServer, tool } from "@anthropic-ai/claude-agent-sdk";
import { z } from "zod";

// Direct WhatsApp Business Cloud API integration — talks straight to
// graph.facebook.com using a permanent System User token generated by hand
// in Meta Business Suite for the WABA/phone number that's already
// provisioned (originally set up via Zernio's embedded signup). No OAuth
// flow here: unlike gmail.ts/instagram.ts, this isn't a per-user login,
// it's a single business number configured once via env vars.
const API_BASE = "https://graph.facebook.com/v21.0";

function getConfig() {
  const accessToken = process.env.WHATSAPP_ACCESS_TOKEN;
  const phoneNumberId = process.env.WHATSAPP_PHONE_NUMBER_ID;
  const businessAccountId = process.env.WHATSAPP_BUSINESS_ACCOUNT_ID;
  if (!accessToken || !phoneNumberId) {
    throw new Error("WHATSAPP_ACCESS_TOKEN / WHATSAPP_PHONE_NUMBER_ID are not set");
  }
  return { accessToken, phoneNumberId, businessAccountId };
}

export function isWhatsappConnected(): boolean {
  return !!process.env.WHATSAPP_ACCESS_TOKEN && !!process.env.WHATSAPP_PHONE_NUMBER_ID;
}

function whatsappHeaders(accessToken: string) {
  return {
    Authorization: `Bearer ${accessToken}`,
    "Content-Type": "application/json",
  };
}

const listWhatsappTemplates = tool(
  "list_whatsapp_templates",
  "List the pre-approved WhatsApp message templates on this business account, with name/language/status. A template is required to message a number that hasn't messaged you in the last 24 hours — use send_whatsapp_template with an APPROVED template's exact name and language for that. Requires WHATSAPP_BUSINESS_ACCOUNT_ID to be configured.",
  {},
  async () => {
    const { accessToken, businessAccountId } = getConfig();
    if (!businessAccountId) {
      return {
        content: [{ type: "text" as const, text: "WHATSAPP_BUSINESS_ACCOUNT_ID is not set — can't list templates." }],
        isError: true,
      };
    }
    const res = await fetch(
      `${API_BASE}/${businessAccountId}/message_templates?fields=name,status,language,category`,
      { headers: whatsappHeaders(accessToken) },
    );
    const json = (await res.json()) as {
      data?: Array<{ name: string; status: string; language: string; category: string }>;
      error?: { message: string };
    };
    if (!res.ok || json.error) {
      return { content: [{ type: "text" as const, text: `Error listing templates: ${json.error?.message ?? res.status}` }], isError: true };
    }
    const templates = json.data ?? [];
    if (!templates.length) {
      return { content: [{ type: "text" as const, text: "No message templates found — create/approve one in Meta Business Suite first." }] };
    }
    const lines = templates.map((t) => `- ${t.name} (${t.language}, ${t.category}): ${t.status}`);
    return { content: [{ type: "text" as const, text: lines.join("\n") }] };
  },
);

const sendWhatsappMessage = tool(
  "send_whatsapp_message",
  "Send a freeform WhatsApp text message to a phone number. Only works within 24 hours of that number's last message to this business (WhatsApp's customer service window) — for a number that hasn't messaged recently or ever, use send_whatsapp_template instead. Irreversible once sent — only call this when explicitly told to send, not just draft.",
  {
    to: z.string().describe("Recipient phone number in international format, e.g. 919088840552 (no + or spaces)"),
    message: z.string(),
  },
  async ({ to, message }) => {
    const { accessToken, phoneNumberId } = getConfig();
    const res = await fetch(`${API_BASE}/${phoneNumberId}/messages`, {
      method: "POST",
      headers: whatsappHeaders(accessToken),
      body: JSON.stringify({
        messaging_product: "whatsapp",
        to,
        type: "text",
        text: { body: message },
      }),
    });
    const json = (await res.json()) as { error?: { message: string }; messages?: Array<{ id: string }> };
    if (!res.ok || json.error) {
      return { content: [{ type: "text" as const, text: `Error sending message: ${json.error?.message ?? res.status}` }], isError: true };
    }
    return { content: [{ type: "text" as const, text: `Message sent to ${to} (id: ${json.messages?.[0]?.id ?? "unknown"}).` }] };
  },
);

const sendWhatsappTemplate = tool(
  "send_whatsapp_template",
  "Send a pre-approved WhatsApp template message to a phone number — the only way to start a fresh conversation with a number outside the 24-hour customer service window. Look up an APPROVED template's exact name/language with list_whatsapp_templates first. Irreversible once sent — only call this when explicitly told to send, not just draft.",
  {
    to: z.string().describe("Recipient phone number in international format, e.g. 919088840552 (no + or spaces)"),
    templateName: z.string().describe("Exact template name from list_whatsapp_templates"),
    languageCode: z.string().describe("Template's language code from list_whatsapp_templates, e.g. en_US"),
    bodyParams: z.array(z.string()).default([]).describe("Values to fill the template body's {{1}}, {{2}}, ... placeholders, in order — omit if the template has none"),
  },
  async ({ to, templateName, languageCode, bodyParams }) => {
    const { accessToken, phoneNumberId } = getConfig();
    const components = bodyParams.length
      ? [{ type: "body", parameters: bodyParams.map((text) => ({ type: "text", text })) }]
      : undefined;
    const res = await fetch(`${API_BASE}/${phoneNumberId}/messages`, {
      method: "POST",
      headers: whatsappHeaders(accessToken),
      body: JSON.stringify({
        messaging_product: "whatsapp",
        to,
        type: "template",
        template: { name: templateName, language: { code: languageCode }, ...(components ? { components } : {}) },
      }),
    });
    const json = (await res.json()) as { error?: { message: string }; messages?: Array<{ id: string }> };
    if (!res.ok || json.error) {
      return { content: [{ type: "text" as const, text: `Error sending template: ${json.error?.message ?? res.status}` }], isError: true };
    }
    return { content: [{ type: "text" as const, text: `Template "${templateName}" sent to ${to} (id: ${json.messages?.[0]?.id ?? "unknown"}).` }] };
  },
);

export const WHATSAPP_TOOLS = [
  "mcp__whatsapp__list_whatsapp_templates",
  "mcp__whatsapp__send_whatsapp_message",
  "mcp__whatsapp__send_whatsapp_template",
];

export const whatsappServer = createSdkMcpServer({
  name: "whatsapp",
  version: "1.0.0",
  instructions:
    "Tools for sending WhatsApp messages directly via the Cloud API. Use send_whatsapp_message for replies within an active 24-hour window, send_whatsapp_template to start a fresh conversation with a number outside that window (check list_whatsapp_templates for a valid template first). Default to describing the draft back to the user before sending; only send directly when explicitly told to.",
  tools: [listWhatsappTemplates, sendWhatsappMessage, sendWhatsappTemplate],
});
